# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: record_file.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'record_file.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11record_file.proto\x12\x10simpleperf.proto\"q\n\x12\x44\x65\x62ugUnwindFeature\x12\x37\n\x04\x66ile\x18\x01 \x03(\x0b\x32).simpleperf.proto.DebugUnwindFeature.File\x1a\"\n\x04\x46ile\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x04\"\xfb\x03\n\x0b\x46ileFeature\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\r\x12\x11\n\tmin_vaddr\x18\x03 \x01(\x04\x12\x34\n\x06symbol\x18\x04 \x03(\x0b\x32$.simpleperf.proto.FileFeature.Symbol\x12\x39\n\x08\x64\x65x_file\x18\x05 \x01(\x0b\x32%.simpleperf.proto.FileFeature.DexFileH\x00\x12\x39\n\x08\x65lf_file\x18\x06 \x01(\x0b\x32%.simpleperf.proto.FileFeature.ElfFileH\x00\x12\x43\n\rkernel_module\x18\x07 \x01(\x0b\x32*.simpleperf.proto.FileFeature.KernelModuleH\x00\x1a\x32\n\x06Symbol\x12\r\n\x05vaddr\x18\x01 \x01(\x04\x12\x0b\n\x03len\x18\x02 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\t\x1a\"\n\x07\x44\x65xFile\x12\x17\n\x0f\x64\x65x_file_offset\x18\x01 \x03(\x04\x1a+\n\x07\x45lfFile\x12 \n\x18\x66ile_offset_of_min_vaddr\x18\x01 \x01(\x04\x1a\x32\n\x0cKernelModule\x12\"\n\x1amemory_offset_of_min_vaddr\x18\x01 \x01(\x04\x42\x13\n\x11type_specific_msgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'record_file_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEBUGUNWINDFEATURE']._serialized_start=39
  _globals['_DEBUGUNWINDFEATURE']._serialized_end=152
  _globals['_DEBUGUNWINDFEATURE_FILE']._serialized_start=118
  _globals['_DEBUGUNWINDFEATURE_FILE']._serialized_end=152
  _globals['_FILEFEATURE']._serialized_start=155
  _globals['_FILEFEATURE']._serialized_end=662
  _globals['_FILEFEATURE_SYMBOL']._serialized_start=458
  _globals['_FILEFEATURE_SYMBOL']._serialized_end=508
  _globals['_FILEFEATURE_DEXFILE']._serialized_start=510
  _globals['_FILEFEATURE_DEXFILE']._serialized_end=544
  _globals['_FILEFEATURE_ELFFILE']._serialized_start=546
  _globals['_FILEFEATURE_ELFFILE']._serialized_end=589
  _globals['_FILEFEATURE_KERNELMODULE']._serialized_start=591
  _globals['_FILEFEATURE_KERNELMODULE']._serialized_end=641
# @@protoc_insertion_point(module_scope)
